<a href="https://colab.research.google.com/github/ajaysuseel/PyTorch-start/blob/main/Theory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Deep Learning



1. Machine learning

2. Deep Learning

3. Perceptron

    a. normal

    b. sigmoid

4. Activation function

    a.sigmoid

    b.ReLU

    c.Leaky ReLU

    d.Softmax
    
5. Training a neural network

    a.Initialization of weights and biases

    b.forward pass

    c.cost computation

    d.back propagation

    d.optimizatiion

6. Forward pass
    -. no bias for input
7. cost function
    a.MSE

    b.Mean absolute error

    c.Binary cross entropy

    d.Categorical cross entropy

8. Optimization
    a.Gradient descent



9. Gradient descent

10. Backpropagation
    
    on differentiating sigmoid-->sigmoid(1-sigmoid)

    chain rule for gradient calculation

    Epoch->one forward+backward pass










#Implementation using pyTorch

In [ ]:
import torch
import numpy as np

###Creating a tensor

In [ ]:
scalar=torch.tensor(0)
scalar

tensor(0)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
vector=torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
vector.ndim

1

In [ ]:
RandTensor=torch.rand((3,2))
RandTensor

tensor([[0.3067, 0.9467],
        [0.4183, 0.0368],
        [0.0083, 0.9995]])

In [ ]:
step=3
rangeTensor=torch.arange(0,13,step)
rangeTensor

tensor([ 0,  3,  6,  9, 12])

In [ ]:
a=torch.tensor([[1,2],[3,4]])
b=a.reshape(4,1)
b

tensor([[1],
        [2],
        [3],
        [4]])

In [ ]:
a[:, 1]

tensor([2, 4])

In [ ]:
a[:,0]

tensor([1, 3])

#Autograd

In [ ]:
x=torch.tensor(2.0,requires_grad=True)
y=torch.tensor(3.0,requires_grad=True)

In [ ]:
z=x**2+3*y
z.backward()

In [ ]:
x.grad.item()

4.0

In [ ]:
y.grad.item()

3.0

In [ ]:
x.item()

2.0

#Convolutional Neural Network


1. Parameter Sharing

2. Stride

3. Kernel

        It is always square while i/p image can be of any dimension

4. Padding

    a.Zero

    b.Mirror

5. Popular Kernels

    Gaussian Blur

    Sharpened

    Edge Detection

    Gaussian Noise

6. Convolution on 3D images

    3D images are RGB scale(Coloured)(depth=3)

7. Pooling layer

    Min

    Max

    Avg(a type of convolution with filter of values= 1/(size*size))

8. Flattening 2D feature map to 1D vector to input to Fully Connected Layer


#Implementation using Pytorch

#Advanced CNN Architecture

1. **VGG**

2. VGG19

    16 convolution layers and 3 F.C layers

    224*224 RGB img

    3*3 convolution layers S=1,P=1

    2*2 max pooling layers S=2

3. Achievements

    ILSVRC : error=37%

    Widely used for transfer learning


4. **Transfer Learning**

    A pretrained model is used as starting point for training a new model for related task

    Multilingual speech training

    Freezing layers

    Vanishing gradient problem in highly stacked networks


5. **ResNet**

    Skip connections
        Two layers in residual block.input of first layer was added to output after two layers

    Residual blocks

    Concatenation(depth increase) vs Addition(no increase)

    Bottle Neck Residual blocks
        For decreasing parameters

        REduction layer -- Processing Layer -- Expamnsion Layer

    


#Implementation with Pytorch

#U-Net



1. Used for image segmentation

    Encoder

    Bridge
                                   
    Decoder

2. Transposed Convolution